version: '2.3'
services:
  frontend-tests:
    build:
      context: ./frontend
      target: test
    environment:
      - CI=true
    depends_on:
      - backend-tests

  backend-tests:
    build:
      context: ./backend
      target: test
    environment:
      - NODE_ENV=test
      - DB_URI=mongodb://test-mongodb:27017/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - test-mongodb

  test-mongodb:
    image: mongo:latest
    ports:
      - 27017
